/**
 * Home Page Controller
 * Manages the home page functionality
 */

class HomePage {
    constructor() {
        this.initialized = false;
    }

    /**
     * Initialize home page
     */
    async init() {
        if (this.initialized) return;

        console.log('Initializing Home Page...');
        
        this.setupEventListeners();
        await this.loadPopularRecipes();
        this.animateStats();
        
        this.initialized = true;
    }

    setupEventListeners() {
        // Hero buttons
        const startCookingBtn = document.querySelector('[data-action="start-cooking"]');
        if (startCookingBtn) {
            startCookingBtn.addEventListener('click', () => {
                window.router.navigateTo('recipe-generator');
            });
        }

        const exploreBtn = document.querySelector('[data-action="explore-recipes"]');
        if (exploreBtn) {
            exploreBtn.addEventListener('click', () => {
                window.router.navigateTo('recipe-generator');
            });
        }

        // View all recipes button
        const viewAllBtn = document.getElementById('view-all-recipes');
        if (viewAllBtn) {
            viewAllBtn.addEventListener('click', () => {
                window.router.navigateTo('recipe-generator');
            });
        }
    }

    /**
     * Load popular recipes
     */
    async loadPopularRecipes() {
        try {
            const data = await window.apiClient.getRecipes({ 
                sort_by: 'createdAt', 
                per_page: 6 
            });

            if (data && data.recipes && data.recipes.length > 0) {
                this.renderPopularRecipes(data.recipes);
            } else {
                // Show empty state if no recipes
                const container = document.getElementById('popular-recipes-grid');
                if (container) {
                    container.innerHTML = `
                        <div class="empty-state" style="grid-column: 1 / -1; text-align: center; padding: 3rem;">
                            <i class="fas fa-utensils" style="font-size: 3rem; color: var(--gray-400); margin-bottom: 1rem;"></i>
                            <h3>No recipes yet</h3>
                            <p style="color: var(--gray-600); margin-bottom: 1rem;">Generate your first recipe using AI!</p>
                            <button class="btn btn-primary" onclick="window.router.navigateTo('recipe-generator')">
                                <i class="fas fa-magic"></i> Generate Recipe
                            </button>
                        </div>
                    `;
                }
            }
        } catch (error) {
            console.error('Error loading popular recipes:', error);
            const container = document.getElementById('popular-recipes-grid');
            if (container) {
                container.innerHTML = `
                    <div class="empty-state" style="grid-column: 1 / -1; text-align: center; padding: 3rem;">
                        <i class="fas fa-exclamation-triangle" style="font-size: 3rem; color: var(--danger); margin-bottom: 1rem;"></i>
                        <h3>Failed to load recipes</h3>
                        <p style="color: var(--gray-600);">Please try again later</p>
                    </div>
                `;
            }
        }
    }

    /**
     * Render popular recipes grid
     */
    renderPopularRecipes(recipes) {
        const container = document.getElementById('popular-recipes-grid');
        if (!container) return;

        container.innerHTML = recipes.map(recipe => this.createRecipeCard(recipe)).join('');

        // Add click listeners
        container.querySelectorAll('.recipe-card').forEach(card => {
            card.addEventListener('click', () => {
                const recipeId = card.dataset.recipeId;
                this.openRecipeModal(recipeId);
            });
        });
    }

    /**
     * Create recipe card HTML
     */
    createRecipeCard(recipe) {
        // Handle both old format (dietary_tags) and new format (dietaryPreferences)
        const tags = recipe.dietaryPreferences || recipe.dietary_tags || [];
        const rating = recipe.rating || 4.5; // Default rating for AI recipes
        const reviewCount = recipe.review_count || 0;
        
        // Handle both old format and new format for time fields
        const totalTime = (recipe.cookTimeMinutes || 0) + (recipe.prepTimeMinutes || 0);
        
        // Handle servings field name variations
        const servings = recipe.servings || recipe.servingSize || 4;
        
        // Show AI badge if generated by AI
        const aiTag = recipe.generatedByAI ? '<span class="ai-badge"><i class="fas fa-robot"></i> AI</span>' : '';

        return `
            <div class="recipe-card" data-recipe-id="${recipe.id}">
                <div class="recipe-image">
                    <i class="fas fa-utensils placeholder-icon"></i>
                    ${aiTag}
                    ${rating > 0 ? `
                    <div class="recipe-rating">
                        <i class="fas fa-star"></i>
                        ${rating.toFixed(1)}${reviewCount > 0 ? ` (${reviewCount})` : ''}
                    </div>
                    ` : ''}
                </div>
                <div class="recipe-content">
                    <h3 class="recipe-title">${recipe.title || 'Untitled Recipe'}</h3>
                    ${recipe.description ? `<p class="recipe-description">${recipe.description.substring(0, 100)}...</p>` : ''}
                    <div class="recipe-meta">
                        ${totalTime > 0 ? `<span><i class="fas fa-clock"></i> ${totalTime} min</span>` : ''}
                        <span><i class="fas fa-users"></i> ${servings} servings</span>
                        ${recipe.difficulty ? `<span><i class="fas fa-signal"></i> ${recipe.difficulty}</span>` : ''}
                    </div>
                    ${tags.length > 0 ? `
                    <div class="recipe-tags">
                        ${tags.slice(0, 3).map(tag => `<span class="tag">${tag}</span>`).join('')}
                    </div>
                    ` : ''}
                    <div class="recipe-actions">
                        <button class="btn btn-outline btn-small">
                            <i class="fas fa-heart"></i>
                            Save
                        </button>
                        <button class="btn btn-primary btn-small">
                            <i class="fas fa-eye"></i>
                            View Recipe
                        </button>
                    </div>
                </div>
            </div>
        `;
    }

    /**
     * Open recipe detail modal
     */
    async openRecipeModal(recipeId) {
        try {
            window.loadingManager.show();

            const data = await window.apiClient.getRecipeById(recipeId);

            if (data.recipe) {
                this.renderRecipeModal(data.recipe);
                window.modalManager.open('recipe-modal');
            }
        } catch (error) {
            console.error('Error loading recipe:', error);
            window.toastManager.error('Failed to load recipe');
        } finally {
            window.loadingManager.hide();
        }
    }

    /**
     * Render recipe modal content
     */
    renderRecipeModal(recipe) {
        const title = document.getElementById('recipe-modal-title');
        const body = document.getElementById('recipe-modal-body');

        if (title) {
            title.textContent = recipe.title;
        }

        if (body) {
            body.innerHTML = `
                <div class="recipe-modal-content">
                    <div class="recipe-header">
                        <div class="recipe-info">
                            <div class="recipe-meta">
                                <span><i class="fas fa-clock"></i> Prep: ${recipe.prepTimeMinutes} min</span>
                                <span><i class="fas fa-fire"></i> Cook: ${recipe.cookTimeMinutes} min</span>
                                <span><i class="fas fa-users"></i> Serves: ${recipe.servingSize}</span>
                            </div>
                        </div>
                    </div>
                    
                    <div class="recipe-sections">
                        <div class="ingredients-section">
                            <h3>Ingredients</h3>
                            <ul class="ingredients-list">
                                ${recipe.ingredients ? recipe.ingredients.map(ing => `
                                    <li>${ing.amount} ${ing.unit} ${ing.name}</li>
                                `).join('') : '<li>No ingredients listed.</li>'}
                            </ul>
                        </div>
                        
                        <div class="instructions-section">
                            <h3>Instructions</h3>
                            <ol class="instructions-list">
                                ${recipe.instructions.split('\n').filter(i => i.trim()).map(instruction => `
                                    <li>${instruction}</li>
                                `).join('')}
                            </ol>
                        </div>
                    </div>
                </div>
            `;
        }
    }

    /**
     * Animate statistics counters
     */
    animateStats() {
        this.animateCounter('total-recipes', 1247);
        this.animateCounter('meal-plans-created', 3892);
        this.animateCounter('users-helped', 12567);
    }

    animateCounter(elementId, targetValue) {
        const element = document.getElementById(elementId);
        if (!element) return;

        const duration = 2000;
        const steps = 60;
        const stepValue = targetValue / steps;
        const stepDuration = duration / steps;

        let currentValue = 0;
        const timer = setInterval(() => {
            currentValue += stepValue;
            if (currentValue >= targetValue) {
                currentValue = targetValue;
                clearInterval(timer);
            }
            element.textContent = Math.floor(currentValue).toLocaleString();
        }, stepDuration);
    }

    /**
     * Called when navigating to this page
     */
    onNavigate() {
        if (!this.initialized) {
            this.init();
        }
    }
}

// Register with router
window.addEventListener('DOMContentLoaded', () => {
    const homePage = new HomePage();
    window.router.register('home', homePage);
    homePage.init(); // Init immediately since home is default page
});
