// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS5lExXFmPc7JuX4u7x6KJKcwryjePPGc',
    appId: '1:821075488273:web:69007a1ad38bdf1c71cbb0',
    messagingSenderId: '821075488273',
    projectId: 'mealy-41bf0',
    authDomain: 'mealy-41bf0.firebaseapp.com',
    storageBucket: 'mealy-41bf0.firebasestorage.app',
    measurementId: 'G-YN5H6CVV8B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDozTqLrnCnU-gL4MRXnidfWUPgMUpw9X8',
    appId: '1:821075488273:android:95ca15c0f554612171cbb0',
    messagingSenderId: '821075488273',
    projectId: 'mealy-41bf0',
    storageBucket: 'mealy-41bf0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGcolNaMVsO933wHzzWDSTxzELg5eqcOM',
    appId: '1:821075488273:ios:020e5b082a23d2a271cbb0',
    messagingSenderId: '821075488273',
    projectId: 'mealy-41bf0',
    storageBucket: 'mealy-41bf0.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGcolNaMVsO933wHzzWDSTxzELg5eqcOM',
    appId: '1:821075488273:ios:020e5b082a23d2a271cbb0',
    messagingSenderId: '821075488273',
    projectId: 'mealy-41bf0',
    storageBucket: 'mealy-41bf0.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDS5lExXFmPc7JuX4u7x6KJKcwryjePPGc',
    appId: '1:821075488273:web:8f710c3c95d0612971cbb0',
    messagingSenderId: '821075488273',
    projectId: 'mealy-41bf0',
    authDomain: 'mealy-41bf0.firebaseapp.com',
    storageBucket: 'mealy-41bf0.firebasestorage.app',
    measurementId: 'G-DQGYTC6MQ9',
  );
}
