"""
Test script for the Suggest Recipes from Fridge feature
"""
import requests
import json

# Configuration
BASE_URL = "http://localhost:5000/api"
DEMO_USER_ID = "demo_user_01"

def test_suggest_recipes_from_fridge():
    """Test the suggest recipes endpoint"""
    print("=" * 60)
    print("Testing Suggest Recipes from Fridge Feature")
    print("=" * 60)
    
    # Step 1: Check if there are items in the fridge
    print("\n1. Checking fridge items...")
    response = requests.get(f"{BASE_URL}/fridge/items")
    
    if response.status_code != 200:
        print(f"❌ Failed to get fridge items: {response.status_code}")
        return False
    
    fridge_data = response.json()
    items = fridge_data.get('data', {}).get('items', [])
    print(f"✅ Found {len(items)} items in fridge")
    
    if len(items) == 0:
        print("\n2. Seeding demo items...")
        seed_response = requests.post(f"{BASE_URL}/fridge/seed-demo-items")
        if seed_response.status_code == 201:
            seed_data = seed_response.json()
            items = seed_data.get('data', {}).get('items', [])
            print(f"✅ Added {len(items)} demo items")
        else:
            print(f"❌ Failed to seed items: {seed_response.status_code}")
            return False
    
    # Display fridge ingredients
    print("\nIngredients in fridge:")
    for item in items:
        name = item.get('ingredientName', item.get('name', 'Unknown'))
        quantity = item.get('quantity', 0)
        unit = item.get('unit', '')
        print(f"  - {name}: {quantity} {unit}")
    
    # Step 2: Call suggest recipes endpoint
    print("\n3. Requesting recipe suggestions...")
    suggest_response = requests.post(
        f"{BASE_URL}/fridge/suggest-recipes",
        json={
            "dietary_preferences": [],
            "difficulty": "medium",
            "servings": 4
        }
    )
    
    print(f"Response Status: {suggest_response.status_code}")
    
    if suggest_response.status_code != 201:
        print(f"❌ Failed to suggest recipes")
        print(f"Response: {suggest_response.text}")
        return False
    
    # Step 3: Display suggested recipe
    result = suggest_response.json()
    recipe_data = result.get('data', {})
    recipe = recipe_data.get('recipe', {})
    similar_recipes = recipe_data.get('similar_recipes', [])
    
    print("\n" + "=" * 60)
    print("✅ RECIPE SUGGESTED SUCCESSFULLY!")
    print("=" * 60)
    
    print(f"\n📝 Recipe Title: {recipe.get('title', 'N/A')}")
    print(f"✨ Generated by AI: {recipe.get('generatedByAI', False)}")
    print(f"🍽️  Servings: {recipe.get('servings', 'N/A')}")
    print(f"⏱️  Cooking Time: {recipe.get('cooking_time', 'N/A')} min")
    print(f"📊 Difficulty: {recipe.get('difficulty', 'N/A')}")
    
    print(f"\n📖 Description:")
    print(f"   {recipe.get('description', 'N/A')}")
    
    print(f"\n🥕 Ingredients ({len(recipe.get('ingredients', []))}):")
    for i, ingredient in enumerate(recipe.get('ingredients', [])[:5], 1):
        ing_name = ingredient if isinstance(ingredient, str) else ingredient.get('name', ingredient)
        print(f"   {i}. {ing_name}")
    if len(recipe.get('ingredients', [])) > 5:
        print(f"   ... and {len(recipe.get('ingredients', [])) - 5} more")
    
    print(f"\n👨‍🍳 Instructions ({len(recipe.get('instructions', []))}):")
    for i, step in enumerate(recipe.get('instructions', [])[:3], 1):
        step_text = step[:100] + "..." if len(step) > 100 else step
        print(f"   {i}. {step_text}")
    if len(recipe.get('instructions', [])) > 3:
        print(f"   ... and {len(recipe.get('instructions', [])) - 3} more steps")
    
    if similar_recipes:
        print(f"\n🔍 Based on these recipes:")
        for rec in similar_recipes[:3]:
            print(f"   - {rec.get('title', rec.get('name', 'Unknown'))}")
    
    nutrition = recipe.get('nutrition')
    if nutrition:
        print(f"\n📊 Nutrition (per serving):")
        if nutrition.get('calories'):
            print(f"   Calories: {nutrition.get('calories')}")
        if nutrition.get('protein'):
            print(f"   Protein: {nutrition.get('protein')}g")
        if nutrition.get('carbs'):
            print(f"   Carbs: {nutrition.get('carbs')}g")
        if nutrition.get('fat'):
            print(f"   Fat: {nutrition.get('fat')}g")
    
    print("\n" + "=" * 60)
    print("✅ TEST PASSED - Suggest Recipes Feature Working!")
    print("=" * 60)
    
    return True

if __name__ == "__main__":
    try:
        success = test_suggest_recipes_from_fridge()
        if not success:
            print("\n❌ Test failed!")
            exit(1)
    except requests.exceptions.ConnectionError:
        print("\n❌ Error: Cannot connect to backend server")
        print("Make sure the Flask server is running on http://localhost:5000")
        exit(1)
    except Exception as e:
        print(f"\n❌ Unexpected error: {e}")
        import traceback
        traceback.print_exc()
        exit(1)
