"""
Test the new fridge-based recipe generation endpoint
"""
import requests
import json

API_BASE = "http://localhost:5000/api"

print("🧪 Testing Fridge-Based Recipe Generation\n")

# Test the endpoint
print("📡 Calling /recipes/generate-from-fridge...")

try:
    response = requests.post(
        f"{API_BASE}/recipes/generate-from-fridge",
        json={
            "dietary_preferences": ["healthy"],
            "max_cooking_time": 45,
            "difficulty": "medium",
            "servings": 4
        },
        headers={"Content-Type": "application/json"}
    )
    
    print(f"Status Code: {response.status_code}")
    
    if response.status_code == 200 or response.status_code == 201:
        data = response.json()
        print("\n✅ SUCCESS!\n")
        
        recipe = data.get('recipe', {})
        print(f"📝 Recipe Title: {recipe.get('title', 'N/A')}")
        print(f"📋 Description: {recipe.get('description', 'N/A')}")
        print(f"🥘 Servings: {recipe.get('servingSize', 'N/A')}")
        print(f"⏱️  Prep Time: {recipe.get('prepTimeMinutes', 'N/A')} min")
        print(f"🔥 Cook Time: {recipe.get('cookTimeMinutes', 'N/A')} min")
        print(f"📊 Difficulty: {recipe.get('difficulty', 'N/A')}")
        
        print(f"\n🛒 Fridge Ingredients Used: {data.get('fridge_ingredients_used', 0)}")
        print(f"⚠️  Ingredients Expiring Soon: {data.get('ingredients_expiring_soon', 0)}")
        print(f"📚 Similar Recipes Found: {data.get('similar_recipes_found', 0)}")
        
        if recipe.get('usedIngredients'):
            print(f"\n✅ Used Ingredients:")
            for ing in recipe['usedIngredients']:
                print(f"   - {ing}")
        
        if recipe.get('prioritizedIngredients'):
            print(f"\n⚠️  Prioritized (Expiring Soon):")
            for ing in recipe['prioritizedIngredients']:
                print(f"   - {ing}")
        
        print(f"\n💾 Recipe ID: {recipe.get('id', 'N/A')}")
        print(f"🤖 Generated by AI: {recipe.get('generatedByAI', False)}")
        print(f"🧊 From Fridge: {recipe.get('fromFridge', False)}")
        
    else:
        print(f"\n❌ Error: {response.status_code}")
        print(response.json())
        
except requests.exceptions.ConnectionError:
    print("❌ Cannot connect to backend server!")
    print("Make sure the server is running: python backend/src/app.py")
    
except Exception as e:
    print(f"❌ Error: {e}")
